# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - 5432:5432

  custom-mongo:
    build: MongoDB/.
    image: custom-mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017
#      for test only
#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongod-express
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    depends_on:
#      - 'custom-mongo'